apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redmine-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine-postgres
  template:
    metadata:
      labels:
        app: redmine-postgres
    spec:
      containers:
      - name: redmine-postgres
        image: postgres:12
        env:
        - name: POSTGRES_PASSWORD
          value: xxxxxxxx
        - name: POSTGRES_DB
          value: redmine
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: redmine-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: redmine-db-data
        nfs:
          server: 140.92.4.4
          path: /iiidevopsNFS
