apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devopswebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopswebui
  template:
    metadata:
      labels:
        app: devopswebui
    spec:
      containers:
      - name: devopswebui
        image: iiiorg/devops-ui:059aff5-10060857
        ports:
        - containerPort: 80
   
